"scrConfigs As screen.'phoneLayout_FluidGridWithHeaderPageLayout_ver3.0'":

    Header_2 As rectangle:
        Fill: =RGBA(0, 0, 0, 0)
        Height: =73
        Width: =Parent.Width
        ZIndex: =3

    lblTitle_2 As label:
        Align: =Align.Center
        BorderColor: =RGBA(166, 166, 166, 1)
        Color: =RGBA(0,156,211,1)
        Height: =73
        Text: =LookUp(StringsOrder,AppKey="scrConfig" && Language=SelectedLanguage,String)
        Width: =1366
        ZIndex: =4

    HeurekaLogo2_2 As image:
        Height: =70
        Image: =heureka_group_logo
        Width: =240
        X: =30
        ZIndex: =5

    HeaderBorder_2 As rectangle:
        BorderColor: =patternColor3.Fill
        BorderThickness: =0.5
        Fill: =RGBA(0, 0, 0, 0)
        Height: =1
        Width: =Parent.Width
        Y: =73
        ZIndex: =6

    bgSetLangStatic As rectangle:
        DisabledFill: =bgSetLangStatic.Fill
        Fill: =RGBA(255, 255, 255, 1)
        FocusedBorderColor: =bgSetLangStatic.BorderColor
        Height: =32
        HoverFill: =bgSetLangStatic.Fill
        PressedFill: =bgSetLangStatic.Fill
        Width: =180
        X: =1181
        Y: =38
        ZIndex: =7

    lblSetLangStatic As label:
        FocusedBorderColor: =lblSetLangStatic.BorderColor
        Font: =Font.'Segoe UI'
        Height: =32
        HoverBorderColor: =lblSetLangStatic.BorderColor
        HoverColor: =lblSetLangStatic.Color
        HoverFill: =lblSetLangStatic.Fill
        OnSelect: =Set(LangMenu,!LangMenu)
        PressedBorderColor: =lblSetLangStatic.BorderColor
        PressedColor: =lblSetLangStatic.Color
        PressedFill: =lblSetLangStatic.Fill
        Text: =LookUp(StringsOrder,AppKey="language" & Upper(SelectedLanguage),String)
        X: =1216
        Y: =38
        ZIndex: =8

    btnLangColExp As icon.ChevronDown:
        Color: =RGBA(128, 128, 128, 1)
        DisabledFill: =btnLangColExp.Fill
        FocusedBorderColor: =btnLangColExp.BorderColor
        Height: =20
        HoverBorderColor: =ColorFade(btnLangColExp.BorderColor, 20%)
        HoverColor: =ColorFade(btnLangColExp.Color, 20%)
        HoverFill: =btnLangColExp.Fill
        Icon: =If(LangMenu,Icon.ChevronUp,Icon.ChevronDown)
        OnSelect: =Set(LangMenu,!LangMenu)
        PressedBorderColor: =ColorFade(btnLangColExp.BorderColor, -20%)
        PressedColor: =ColorFade(btnLangColExp.Color, -20%)
        PressedFill: =btnLangColExp.Fill
        Width: =20
        X: =1187
        Y: =44
        ZIndex: =9

    btnLangSetEN As button:
        BorderColor: =
        BorderThickness: =0
        Color: =RGBA(0, 0, 0, 1)
        DisabledColor: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(210, 230, 251, 1)
        FocusedBorderColor: =btnLangSetEN.BorderColor
        FocusedBorderThickness: =0
        Font: =
        FontWeight: =FontWeight.Normal
        Height: =bgSetLangStatic.Height
        HoverBorderColor: =ColorFade(btnLangSetEN.BorderColor, 20%)
        HoverFill: =
        OnSelect: =Set(SelectedLanguage,"en");Set(LangMenu,false);Set(UserSettings,false)
        PaddingBottom: =0
        PaddingLeft: =0
        PaddingRight: =0
        PaddingTop: =0
        PressedBorderColor: =btnLangSetEN.Fill
        PressedColor: =btnLangSetEN.Fill
        PressedFill: =
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =13
        Text: =LookUp(StringsOrder,AppKey="languageEN" && Language=SelectedLanguage,String)
        Visible: =LangMenu
        Width: =bgSetLangStatic.Width-30
        X: =1181
        Y: =75
        ZIndex: =10

    btnLangSetCZ As button:
        BorderColor: =
        BorderThickness: =0
        Color: =RGBA(0, 0, 0, 1)
        DisabledColor: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(210, 230, 251, 1)
        FocusedBorderColor: =btnLangSetCZ.BorderColor
        FocusedBorderThickness: =0
        FontWeight: =FontWeight.Normal
        Height: =bgSetLangStatic.Height
        HoverBorderColor: =ColorFade(btnLangSetCZ.BorderColor, 20%)
        HoverFill: =
        OnSelect: =Set(SelectedLanguage,"cs");Set(LangMenu,false);Set(UserSettings,false)
        PaddingBottom: =0
        PaddingLeft: =0
        PaddingRight: =0
        PaddingTop: =0
        PressedBorderColor: =btnLangSetCZ.Fill
        PressedColor: =btnLangSetCZ.Fill
        PressedFill: =
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =13
        Text: =LookUp(StringsOrder,AppKey="languageCS" && Language=SelectedLanguage,String)
        Visible: =LangMenu
        Width: =bgSetLangStatic.Width-30
        X: =1181
        Y: =113
        ZIndex: =11

    btnLangSetHU As button:
        BorderColor: =
        BorderThickness: =0
        Color: =RGBA(0, 0, 0, 1)
        DisabledColor: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(210, 230, 251, 1)
        FocusedBorderColor: =btnLangSetHU.BorderColor
        FocusedBorderThickness: =0
        FontWeight: =FontWeight.Normal
        Height: =bgSetLangStatic.Height
        HoverBorderColor: =ColorFade(btnLangSetHU.BorderColor, 20%)
        HoverFill: =
        OnSelect: =Set(SelectedLanguage,"hu");Set(LangMenu,false);Set(UserSettings,false)
        PaddingBottom: =0
        PaddingLeft: =0
        PaddingRight: =0
        PaddingTop: =0
        PressedBorderColor: =btnLangSetHU.Fill
        PressedColor: =btnLangSetHU.Fill
        PressedFill: =
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =13
        Text: =LookUp(StringsOrder,AppKey="languageHU" && Language=SelectedLanguage,String)
        Visible: =LangMenu
        Width: =bgSetLangStatic.Width-30
        X: =1181
        Y: =153
        ZIndex: =12

    btnLangSetHR As button:
        BorderColor: =
        BorderThickness: =0
        Color: =RGBA(0, 0, 0, 1)
        DisabledColor: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(210, 230, 251, 1)
        FocusedBorderColor: =btnLangSetHR.BorderColor
        FocusedBorderThickness: =0
        FontWeight: =FontWeight.Normal
        Height: =bgSetLangStatic.Height
        HoverBorderColor: =ColorFade(btnLangSetHR.BorderColor, 20%)
        HoverFill: =
        OnSelect: =Set(SelectedLanguage,"hr");Set(LangMenu,false);Set(UserSettings,false)
        PaddingBottom: =0
        PaddingLeft: =0
        PaddingRight: =0
        PaddingTop: =0
        PressedBorderColor: =btnLangSetHR.Fill
        PressedColor: =btnLangSetHR.Fill
        PressedFill: =
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =13
        Text: =LookUp(StringsOrder,AppKey="languageHR" && Language=SelectedLanguage,String)
        Visible: =LangMenu
        Width: =bgSetLangStatic.Width-30
        X: =1181
        Y: =192
        ZIndex: =13

    btnLangSetSL As button:
        BorderColor: =
        BorderThickness: =0
        Color: =RGBA(0, 0, 0, 1)
        DisabledColor: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(210, 230, 251, 1)
        FocusedBorderColor: =btnLangSetSL.BorderColor
        FocusedBorderThickness: =0
        FontWeight: =FontWeight.Normal
        Height: =bgSetLangStatic.Height
        HoverBorderColor: =ColorFade(btnLangSetSL.BorderColor, 20%)
        HoverFill: =
        OnSelect: =Set(SelectedLanguage,"sl");Set(LangMenu,false);Set(UserSettings,false)
        PaddingBottom: =0
        PaddingLeft: =0
        PaddingRight: =0
        PaddingTop: =0
        PressedBorderColor: =btnLangSetSL.Fill
        PressedColor: =btnLangSetSL.Fill
        PressedFill: =
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Size: =13
        Text: =LookUp(StringsOrder,AppKey="languageSL" && Language=SelectedLanguage,String)
        Visible: =LangMenu
        Width: =bgSetLangStatic.Width-30
        X: =1181
        Y: =232
        ZIndex: =14

    tglAdminMode As toggleSwitch:
        Default: =true
        X: =240
        Y: =141
        ZIndex: =15

    Label3 As label:
        Text: ="Admin Mode"
        X: =49
        Y: =135
        ZIndex: =16

    Label3_1 As label:
        Text: ="Admin email"
        X: =49
        Y: =180
        ZIndex: =17

    txtAdminEmail As text:
        Default: ="admin.ocko@heurekagroup.onmicrosoft.com"
        Width: =947
        X: =240
        Y: =180
        ZIndex: =18

    Label3_2 As label:
        Text: ="Approval center"
        X: =49
        Y: =228
        ZIndex: =19

    txtApprovalCenterWeb As text:
        Default: |-
            ="https://heurekagroup.sharepoint.com/sites/HeurekaGroup_TEST/ApprovalCenter"
        Width: =947
        X: =240
        Y: =228
        ZIndex: =20

    "'List Order name' As label":
        Text: ="List Order name"
        X: =49
        Y: =282
        ZIndex: =21

    txtListOrderName As text:
        Default: ="DMSOrder"
        Width: =947
        X: =240
        Y: =282
        ZIndex: =22

    Label3_4 As label:
        Text: ="List Invoice name"
        X: =49
        Y: =338
        ZIndex: =23

    txtListInvoiceName As text:
        Default: ="DMSInvoice"
        Width: =947
        X: =240
        Y: =338
        ZIndex: =24

    Label3_5 As label:
        Text: ="Contract web"
        X: =49
        Y: =390
        ZIndex: =25

    txtContractWeb As text:
        Default: |-
            ="https://heurekagroup.sharepoint.com/sites/HeurekaGroup_TEST/Contracts/"
        Width: =947
        X: =240
        Y: =390
        ZIndex: =26

    Label3_6 As label:
        Text: ="List Contract name"
        X: =49
        Y: =443
        ZIndex: =27

    txtListContractName As text:
        Default: ="DMSContract"
        Width: =947
        X: =240
        Y: =443
        ZIndex: =28

    Label3_7 As label:
        Text: ="APP ID"
        X: =49
        Y: =498
        ZIndex: =29

    txtAPPID As text:
        Default: ="1ded8545-e7ed-4f88-9497-d25920496beb"
        Width: =947
        X: =240
        Y: =498
        ZIndex: =30

    Label3_8 As label:
        Text: ="Tenant ID"
        X: =49
        Y: =551
        ZIndex: =31

    txtTenantID As text:
        Default: ="7d4b1c11-92c5-46f6-b07a-f7f95fc039c0"
        Width: =947
        X: =240
        Y: =551
        ZIndex: =32

    Label3_9 As label:
        Text: ="Mobile App URL"
        X: =49
        Y: =604
        ZIndex: =33

    txtWebAppURL As text:
        Default: |-
            ="https://apps.powerapps.com/play/0a9f8026-9426-41fa-a58b-75e0289217f9?tenantId=7d4b1c11-92c5-46f6-b07a-f7f95fc039c0"
        Width: =947
        X: =240
        Y: =604
        ZIndex: =34

