"Settings As screen.'phoneLayout_FluidGridWithHeaderPageLayout_ver3.0'":

    patternColor6 As rectangle:
        BorderColor: =RGBA(204, 204, 204, 1)
        BorderThickness: =1
        Fill: =RGBA(203, 102, 102, 1)
        Height: =42
        Width: =122
        X: =1094
        Y: =493
        ZIndex: =1

    lblColors As label:
        Text: |-
            ="Colors:"
        X: =1016
        Y: =120
        ZIndex: =2

    lblButtons As label:
        Text: |-
            ="Buttons:"
        X: =794
        Y: =120
        ZIndex: =3

    Header As rectangle:
        Fill: =RGBA(0, 0, 0, 0)
        Height: =59
        Width: =Parent.Width
        ZIndex: =4

    lblTitle As label:
        Align: =Align.Center
        BorderColor: =RGBA(166, 166, 166, 1)
        Color: =RGBA(0,156,211,1)
        Height: =73
        Text: ="[Title]"
        Width: =1366
        ZIndex: =5

    HeurekaLogo2 As image:
        Height: =74
        Image: =heureka_group_logo
        Width: =240
        X: =30
        ZIndex: =6

    HeaderBorder As rectangle:
        BorderColor: =patternColor3.Fill
        BorderThickness: =1
        Fill: =RGBA(0, 0, 0, 0)
        Height: =1
        Width: =Parent.Width
        Y: =73
        ZIndex: =7

    patternColor1 As rectangle:
        BorderColor: =RGBA(204, 204, 204, 1)
        BorderThickness: =1
        Fill: =RGBA(0,156,211,1)
        Height: =42
        Width: =122
        X: =1094
        Y: =160
        ZIndex: =8

    patternColor2 As rectangle:
        BorderColor: =RGBA(204, 204, 204, 1)
        BorderThickness: =1
        Fill: =RGBA(239,112,1,1)
        Height: =42
        Width: =122
        X: =1094
        Y: =224
        ZIndex: =9

    patternColor3 As rectangle:
        BorderColor: =RGBA(204, 204, 204, 1)
        BorderThickness: =1
        Fill: =RGBA(193,193,193,1)
        Height: =42
        Width: =122
        X: =1094
        Y: =292
        ZIndex: =10

    patternColor4 As rectangle:
        BorderColor: =RGBA(204, 204, 204, 1)
        BorderThickness: =1
        Fill: =RGBA(0,126,170,1)
        Height: =42
        Width: =122
        X: =1094
        Y: =355
        ZIndex: =11

    patternColor5 As rectangle:
        BorderColor: =RGBA(204, 204, 204, 1)
        BorderThickness: =1
        Fill: =RGBA(244,244,244,1)
        Height: =42
        Width: =122
        X: =1094
        Y: =420
        ZIndex: =12

    patternButton As button:
        BorderColor: =patternColor3.DisabledFill
        BorderThickness: =0.5
        Color: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(0, 0, 0, 0)
        FocusedBorderColor: =patternColor4.Fill
        FocusedBorderThickness: =0.5
        HoverBorderColor: =patternColor4.Fill
        HoverColor: =
        HoverFill: =
        PressedBorderColor: =patternColor4.Fill
        PressedColor: =
        PressedFill: =ColorFade(patternColor3.Fill, 90%)
        Text: ="Button"
        X: =844
        Y: =162
        ZIndex: =13

    patternLabel As label:
        Color: =labelSettings.Color
        Font: =labelSettings.Font
        Size: =labelSettings.Size
        Text: ="Text"
        Tooltip: =labelSettings.Tooltip
        X: =30
        Y: =184
        ZIndex: =14

    patternDropDown As dropdown:
        BorderColor: =patternColor3.Fill
        BorderThickness: =1
        ChevronBackground: =
        ChevronFill: =patternColor1.Fill
        ChevronHoverBackground: =patternColor4.Fill
        FocusedBorderColor: =patternColor4.Fill
        FocusedBorderThickness: =1
        HoverBorderColor: =patternColor4.Fill
        HoverFill: =ColorFade(patternColor3.Fill, 90%)
        Items: =DropDownSample
        SelectionColor: =White
        SelectionFill: =patternColor4.Fill
        X: =30
        Y: =296
        ZIndex: =15

    patternComboBox As combobox:
        BorderColor: =patternColor3.Fill
        BorderThickness: =1
        ChevronBackground: =
        ChevronFill: =patternColor1.Fill
        ChevronHoverBackground: =patternColor4.Fill
        FocusedBorderColor: =patternColor4.Fill
        FocusedBorderThickness: =1
        HoverBorderColor: =patternColor4.Fill
        HoverFill: =ColorFade(patternColor3.Fill, 90%)
        Items: =ComboBoxSample
        SearchItems: =Search(ComboBoxSample,patternComboBox.SearchText,"Value1")
        SelectionColor: =White
        SelectionFill: =patternColor4.Fill
        X: =30
        Y: =357
        ZIndex: =16

    patternDatePicker As datepicker:
        BorderColor: =patternColor3.Fill
        BorderThickness: =1
        FocusedBorderColor: =patternColor4.Fill
        FocusedBorderThickness: =1
        IconBackground: =White
        IconFill: =patternColor4.Fill
        X: =30
        Y: =420
        ZIndex: =17

    patternToggle As toggleSwitch:
        HoverBorderColor: =
        PressedBorderColor: =
        TrueFill: =patternColor4.Fill
        TrueHoverFill: =patternColor4.Fill
        X: =30
        Y: =493
        ZIndex: =18

    patternTextInput As text:
        BorderColor: =patternColor3.Fill
        BorderThickness: =1
        Default: =""
        FocusedBorderColor: =patternColor4.Fill
        FocusedBorderThickness: =1
        HoverBorderColor: =patternColor4.Fill
        HoverFill: =ColorFade(patternColor3.Fill, 90%)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Width: =328
        X: =30
        Y: =240
        ZIndex: =19

    labelSettings As label:
        Height: =35
        Text: ="Vzor"
        X: =644
        Y: =122
        ZIndex: =20

    container As groupContainer:
        Fill: |-
            =Switch(
                Param("theme"),
                "contrast",
                Black,
                "dark",
                ColorValue("#201F1E"), // NeutralWebGray180
                ColorValue("#F3F2F1") // NeutralWebGray20
            )
        Height: =113
        Width: =175
        X: =488
        Y: =240
        ZIndex: =21

        lblContainer As label:
            Align: =Align.Center
            BorderColor: =
            BorderThickness: =
            Color: |
                =// Non-variable colors, while variable is established
                Switch(
                    Param("theme"),
                    "contrast",
                    White,
                    "dark",
                    White,
                    ColorValue("#252423") // NeutralWebGray190
                )
            DisabledBorderColor: =
            DisabledColor: =
            DisabledFill: =
            DisplayMode: =DisplayMode.View
            Fill: =Transparent
            FocusedBorderColor: =
            FocusedBorderThickness: =
            Font: =Font.'Segoe UI'
            Height: =32
            HoverBorderColor: =
            HoverColor: =
            HoverFill: =
            PressedBorderColor: =
            PressedColor: =
            PressedFill: =
            Size: =
            Text: ="Container"
            Width: =Parent.Width
            Y: =
            ZIndex: =3

    dpContractDateOfSignature_background_1 As datepicker:
        BorderColor: |-
            =//If(dpOrderDate_validation,patternColor3.Fill,patternColor6.Fill)
            patternColor3.Fill
        BorderThickness: =1
        DefaultDate: =
        DisplayMode: |-
            =If((customFormMode = FormMode.Edit && ContractSHPItem.'Actual Phase' = "100"),
                DisplayMode.Edit,
                If(customFormMode = FormMode.Edit,
                    DisplayMode.Disabled,
                    DisplayMode.Disabled
                )
            )
        Fill: =RGBA(237, 237, 237, 1)
        FocusedBorderColor: =patternColor4.Fill
        FocusedBorderThickness: =1
        IconBackground: =RGBA(237, 237, 237, 1)
        IconFill: =Transparent
        InputTextPlaceholder: =
        Tooltip: =
        Width: =484
        X: =30
        Y: =622
        ZIndex: =22

    "dpContractDateOfSignature_1 As 'Date picker'":
        AcceptsFocus: =false
        DisplayMode: |-
            =If((customFormMode = FormMode.Edit && ContractSHPItem.'Actual Phase' = "100"),
                DisplayMode.Edit,
                If(customFormMode = FormMode.Edit,
                    DisplayMode.Disabled,
                    DisplayMode.Disabled
                )
            )
        Font: =Font.'Open Sans'
        FontSize: =14
        FontWeight: ="normal"
        Height: =39
        IconSize: =16
        InitialPickerDate: =
        PaddingBottom: =0
        PaddingTop: =0
        PCFTeamsTheme: =TeamsTheme.Default
        ShowGoToToday: =true
        Value: |-
            =If(customFormMode = FormMode.New,
                Today(),
                ContractSHPItem.DMSContractDateOfSignature
            )
        Visible: =true
        Width: =483
        X: =30
        Y: =623
        ZIndex: =23

